spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
    show-sql: false
    properties:
      'hibernate.jdbc.lob.non_contextual_creation': true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  liquibase.change-log: classpath:changelog/db.changelog.xml
  jackson:
    date-format:


logging.level:
  org.apache.cxf: info
  io.swagger: info

management.endpoints.web.exposure.include: ['health', 'info' ]
